[project]
name = 'fak-ai'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.faktory-dex-trait-v1]
path = 'contracts/faktory-dex-trait-v1.clar'
clarity_version = 2
epoch = 2.5

[contracts.faktory-trait-v1]
path = 'contracts/faktory-trait-v1.clar'
clarity_version = 2
epoch = 2.5

[contracts.name-faktory]
path = 'contracts/name-faktory.clar'
clarity_version = 2
epoch = 2.5

[contracts.name-faktory-dex]
path = 'contracts/name-faktory-dex.clar'
clarity_version = 2
epoch = 2.5

[contracts.stx-ai-dex]
path = 'contracts/stx-ai-dex.clar'
clarity_version = 2
epoch = 2.5

[contracts.stx-ai-token]
path = 'contracts/stx-ai-token.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
